import Head from "next/head";
import styles from "./index.module.css";
import Grid from "../components/Grids/Grid";
import Info from "../components/Info/Info";

export default function HomePage() {
  return (
      <div className={styles.main}>
        <div className={styles.sidebar}>
          <div className="bg-blue-800">
            <Head>
              <title>Responsive Side-Navbar</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/pro.ico" />
            </Head>
            <SideNavbar />
          </div>
        </div>
    
          </div>
  );
}
